# Generated by Django 4.2.4 on 2023-11-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteams',
            name='is_team_lead',
            field=models.BooleanField(default=False),
        ),
    ]
