# Generated by Django 4.2.4 on 2023-08-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('QA', 'QA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('QA', 'QA')], default='None', max_length=20, null=True),
        ),
    ]
