# Generated by Django 4.2.4 on 2023-08-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0002_alter_project_type_alter_user_photo_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
