# Generated by Django 4.2.4 on 2023-08-14 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.FileField(null=True, upload_to='media/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('QA', 'QA')], default='None', max_length=20, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_app.login')),
            ],
        ),
        migrations.AlterField(
            model_name='logs',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_app.users'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_app.users'),
        ),
        migrations.AlterField(
            model_name='task',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_app.users'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
