# Generated by Django 4.2.4 on 2023-08-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0004_users_alter_logs_user_alter_projectteam_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Cancel', 'Cancel'), ('Onhold', 'Onhold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Website', 'Website'), ('Web Application', 'Web Application'), ('Mobile Application', 'Mobile Application')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Cancel', 'Cancel'), ('Onhold', 'Onhold')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Cancel', 'Cancel'), ('Onhold', 'Onhold')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
    ]
