# Generated by Django 4.2.4 on 2023-08-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0007_users_phone_alter_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
