# Generated by Django 4.2.4 on 2023-08-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
