# Generated by Django 4.2.4 on 2023-08-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0010_alter_subtask_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='None', null=True, upload_to='media/'),
        ),
    ]
