# Generated by Django 4.2.4 on 2023-08-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0011_alter_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='logtext',
            field=models.CharField(max_length=100),
        ),
    ]
