# Generated by Django 4.2.4 on 2023-08-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0015_alter_project_projectname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='On', max_length=10)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment_app.users')),
            ],
        ),
    ]
